# Cloud Run service definition
# Deploy with: gcloud run services replace cloudrun-service.yaml

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: crud-api
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"   # scale to zero when idle (saves cost)
        autoscaling.knative.dev/maxScale: "10"
        run.googleapis.com/cpu-throttling: "true"
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
        - image: gcr.io/YOUR_PROJECT_ID/crud-api:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "1"
              memory: 512Mi
          env:
            - name: PORT
              value: "8080"
            # Uncomment for Cloud SQL:
            # - name: DATABASE_URL
            #   valueFrom:
            #     secretKeyRef:
            #       name: db-url
            #       key: latest
